@startuml ASME SDC 25-26 Diagram

package Power {
usecase "22 V Battery" as B
usecase "12V LM2596 Buck Converter" as BC12
usecase "6V LM2596 Buck Converter" as BC6
usecase "5V LM2596 Buck Converter" as BC5
}

package Drivetrain {
    usecase "L298N Motor Driver" as L298N
    usecase "12V DC Motor 1" as DC1
    usecase "12V DC Motor 2" as DC2
}

package Disposal {
    usecase "Sorting Servo Motor 6V" as SSM
    usecase "MOSFET (12V)" as MOS12
}

package Collection {
    usecase "Collection Servo Motor 6V" as CSM
    usecase "MOSFET (6V) #1" as MOS61
}

package Sorting {
    usecase "Disposal DC Motor 6V" as DSM
    usecase "MOSFET (6V) #2" as MOS62
    usecase "Disposal Motor Driver?" as DMD
}


(Xbox Controller) ..> (ESP32-S3 Devkit) #blue;text:blue : Receive BLE Controller Inputs


'POWER
B --> BC12 #black;text:black : Reduce to 12V
B --> BC6 #black;text:black : Reduce to 6V
B --> BC5 #black;text:black : Reduce to 5V

BC12 --> L298N #black;text:black : 12V Supply
L298N-> DC1 #black;text:black : Power Motor
L298N --> DC2 #black;text:black : Power Motor

BC5 --> (ESP32-S3 Devkit) #black;text:black : Vin / 5V Pin

BC6 --> SSM #black;text:black : Power Servo
BC6 --> CSM #black;text:black : Power Servo
BC6 --> DMD #black;text:black : Power Disposal Motor Driver, LM298N?
DMD --> DSM #black;text:black : Motor Drive Disposal Motor

'Pins
(ESP32-S3 Devkit) ..> L298N #blue;text:blue : IN1, IN2, IN3, IN4, ENA (PWM), ENB (PWM)
' IN1-->GPIO6, IN2-->GPIO7, IN3-->GPIO15, IN4-->GPIO16, ENA-->GPIO17, ENB-->GPIO18

(ESP32-S3 Devkit) ..> SSM #blue;text:blue : GPIO9 PWM
(ESP32-S3 Devkit) ..> CSM #blue;text:blue : GPIO10 PWM
(ESP32-S3 Devkit) ..> DMD #blue;text:blue : GPIO11 PWM


@enduml